# Generated by Django 4.2.7 on 2023-12-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_categoria_noticia_categoria_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='resumen',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
